const categories = {
  games: { number:"01 / GAMES", title:"Games", description:"Browser-ready arcade runs, music quizzes, stories, and small worlds.", feature:{label:"PLAYGROUND",title:"Pick a game and jump in.",copy:"Every original game stays in its existing home. The library is simply a better way to find it.",accent:"games"}, cards:[
    {title:"Mini Games",type:"ARCADE",copy:"RocketBoost, 2048, Asteroids, and more browser-sized challenges.",href:"Mini-Games.html",art:"arcade"},
    {title:"Music Quizzes",type:"QUIZ",copy:"Test your ear across decades, artists, and genres.",href:"Music-Quizes.html",art:"music"},
    {title:"Children's Games",type:"LEARN & PLAY",copy:"Friendly learning games and interactive stories for curious players.",href:"Children-Games.html",art:"kids"},
    {title:"Sandbox",type:"EXPERIMENTS",copy:"Loose ideas, visual toys, and projects that ignore neat categories.",href:"SandBox.html",art:"sandbox"}
  ]},
  apps: { number:"02 / APPS", title:"Apps", description:"Interactive tools, visual stories, and useful experiments.", feature:{label:"FEATURED LOCAL TOOL",title:"RSSI Monitor",copy:"A private Windows desktop monitor for live Wi-Fi signal strength, connection details, and a rolling 60-second RSSI graph.",accent:"rssi",href:"downloads/rssi-monitor-source.zip",cta:"DOWNLOAD SOURCE"}, cards:[
    {title:"RSSI Monitor",type:"WINDOWS / PYTHON",image:"assets/rssi-monitor-preview.svg",copy:"Tracks SSID, BSSID, channel, signal quality, link rates, and measured or clearly labelled estimated RSSI—locally, with no telemetry.",href:"downloads/rssi-monitor-source.zip",art:"rssi",cta:"DOWNLOAD .ZIP"},
    {title:"Gemini Lava Lamp",type:"SVG / INTERACTIVE",copy:"A playful, thermodynamic lava lamp with color presets and adjustable controls.",href:"Gemini_Lava_Lamp/",art:"lava",cta:"LAUNCH APP"},
    {title:"The Lyric Prism",type:"DATA STORY / REACT",copy:"Explore six recurring themes across 47 years of Pink Floyd lyrics.",href:"https://wodinoneeye.github.io/Pink_Floyd_Data_Set/",art:"prism",cta:"OPEN APP"},
    {title:"The Picture Index",type:"DATA STORY / IMDb",copy:"An interactive study of audience taste across IMDb's Top 700 films.",href:"https://the-picture-index.booradly.chatgpt.site",art:"picture",cta:"OPEN APP"},
    {title:"The Assurance Index",type:"FINANCIAL RISK",copy:"Explore risk, compliance, fraud, AI adoption, and workload across the Big Four.",href:"https://wodinoneeye.github.io/Big_4_Financial_Risk_Insights/",art:"assurance",cta:"OPEN APP"}
  ]},
};
const content=document.querySelector(".library-content"),cards=document.querySelector("#project-cards"),banner=document.querySelector("#featured-banner");
function cardMarkup(card){const external=card.href.startsWith("http")?' target="_blank" rel="noopener"':"",media=card.image?`<img src="${card.image}" alt="RSSI Monitor interface preview">`:`<div class="card-art ${card.art}" aria-hidden="true"><i></i><i></i><i></i></div>`;return `<a class="project-card" href="${card.href}"${external}><div class="card-media">${media}</div><div class="card-copy"><span>${card.type}</span><h2>${card.title}</h2><p>${card.copy}</p><strong>${card.cta} <b>↗</b></strong></div></a>`}
function render(){const key=location.hash.slice(1),category=categories[key]||categories.apps,activeKey=categories[key]?key:"apps";document.querySelector("#category-number").textContent=category.number;document.querySelector("#category-title").textContent=category.title;document.querySelector("#category-description").textContent=category.description;document.querySelector("#project-count").textContent=String(category.cards.length).padStart(2,"0");document.querySelector("#section-label").textContent=`${category.title.toUpperCase()} / AVAILABLE NOW`;content.dataset.category=activeKey;document.querySelectorAll("[data-category-link]").forEach(link=>link.classList.toggle("active",link.dataset.categoryLink===activeKey));banner.className=`featured-banner ${category.feature.accent}`;banner.innerHTML=`<span>${category.feature.label}</span><h2>${category.feature.title}</h2><p>${category.feature.copy}</p>${category.feature.cta?`<a href="${category.feature.href}">${category.feature.cta} <b>↗</b></a>`:""}`;cards.innerHTML=category.cards.map(cardMarkup).join("");document.title=`${category.title} — BooRadly`}
Object.entries(categories).forEach(([key,category])=>document.querySelector(`[data-count="${key}"]`).textContent=category.cards.length);window.addEventListener("hashchange",render);render();
